In [1]:
#Import libraries 
import pandas as pd

In [2]:
# Read in all csv stats categories
AstPerGame = pd.read_csv('/Users/bryanwenger/Desktop/Desktop_Master/Coding/github_projects/marchmadness_2023/MarchMadness_2023/data_sets/AstPerGame_2023.csv')
AstTORatio = pd.read_csv('/Users/bryanwenger/Desktop/Desktop_Master/Coding/github_projects/marchmadness_2023/MarchMadness_2023/data_sets/AstTORatio_2023.csv')
BlocksPerGame = pd.read_csv('/Users/bryanwenger/Desktop/Desktop_Master/Coding/github_projects/marchmadness_2023/MarchMadness_2023/data_sets/BlocksPerGame_2023.csv')
FldGlPct = pd.read_csv('/Users/bryanwenger/Desktop/Desktop_Master/Coding/github_projects/marchmadness_2023/MarchMadness_2023/data_sets/FldGl%_2023.csv')
FldGlPctDef = pd.read_csv('/Users/bryanwenger/Desktop/Desktop_Master/Coding/github_projects/marchmadness_2023/MarchMadness_2023/data_sets/FldGl%Def_2023.csv')
FoulsPerGame = pd.read_csv('/Users/bryanwenger/Desktop/Desktop_Master/Coding/github_projects/marchmadness_2023/MarchMadness_2023/data_sets/FoulsPerGame_2023.csv')
FTPct = pd.read_csv('/Users/bryanwenger/Desktop/Desktop_Master/Coding/github_projects/marchmadness_2023/MarchMadness_2023/data_sets/FT%_2023.csv')
ReboundMargin = pd.read_csv('/Users/bryanwenger/Desktop/Desktop_Master/Coding/github_projects/marchmadness_2023/MarchMadness_2023/data_sets/ReboundMargin_2023.csv')
ScoringDefense = pd.read_csv('/Users/bryanwenger/Desktop/Desktop_Master/Coding/github_projects/marchmadness_2023/MarchMadness_2023/data_sets/ScoringDefense_2023.csv')
ScoringMargin = pd.read_csv('/Users/bryanwenger/Desktop/Desktop_Master/Coding/github_projects/marchmadness_2023/MarchMadness_2023/data_sets/ScoringMargin_2023.csv')
ScoringOffense = pd.read_csv('/Users/bryanwenger/Desktop/Desktop_Master/Coding/github_projects/marchmadness_2023/MarchMadness_2023/data_sets/ScoringOffense_2023.csv')
StlsPerGame = pd.read_csv('/Users/bryanwenger/Desktop/Desktop_Master/Coding/github_projects/marchmadness_2023/MarchMadness_2023/data_sets/StlsPerGame_2023.csv')
ThreePtFGPct = pd.read_csv('/Users/bryanwenger/Desktop/Desktop_Master/Coding/github_projects/marchmadness_2023/MarchMadness_2023/data_sets/ThreePtFG%_2023.csv')
ThreePtFGDef = pd.read_csv('/Users/bryanwenger/Desktop/Desktop_Master/Coding/github_projects/marchmadness_2023/MarchMadness_2023/data_sets/ThreePtFGDef_2023.csv')
ThreePtFGPerGame = pd.read_csv('/Users/bryanwenger/Desktop/Desktop_Master/Coding/github_projects/marchmadness_2023/MarchMadness_2023/data_sets/ThreePtFGPerGame_2023.csv')
TOMargin = pd.read_csv('/Users/bryanwenger/Desktop/Desktop_Master/Coding/github_projects/marchmadness_2023/MarchMadness_2023/data_sets/TOMargin_2023.csv')
TOPerGame = pd.read_csv('/Users/bryanwenger/Desktop/Desktop_Master/Coding/github_projects/marchmadness_2023/MarchMadness_2023/data_sets/TOPerGame_2023.csv')
WLPct = pd.read_csv('/Users/bryanwenger/Desktop/Desktop_Master/Coding/github_projects/marchmadness_2023/MarchMadness_2023/data_sets/WL%_2023.csv')

In [3]:
AstPerGame.head()

   Rank                            Team  GM    W-L  AST   APG
0    29  A&M-Corpus Christi (Southland)  33  23-10  518  15.7
1    28         Abilene Christian (WAC)  30  13-17  471  15.7
2    39       Air Force (Mountain West)  32  14-18  491  15.3
3   153                     Akron (MAC)  33  22-11  443  13.4
4   202              Alabama A&M (SWAC)  33  15-18  419  12.7

In [4]:
AstPerGame.rename(columns = {'Rank':'AstPerGame_Rank'}, inplace = True)
AstTORatio.rename(columns = {'Rank':'AstTORatio_Rank'}, inplace = True)
BlocksPerGame.rename(columns = {'Rank':'BlocksPerGame_Rank'}, inplace = True)
FldGlPct.rename(columns = {'Rank':'FldGlPct_Rank'}, inplace = True)
FldGlPctDef.rename(columns = {'Rank':'FldGlPctDef_Rank'}, inplace = True)
FoulsPerGame.rename(columns = {'Rank':'FoulsPerGame_Rank'}, inplace = True)
FTPct.rename(columns = {'Rank':'FTPct_Rank'}, inplace = True)
ReboundMargin.rename(columns = {'Rank':'ReboundMargin_Rank'}, inplace = True)
ScoringDefense.rename(columns = {'Rank':'ScoringDefense_Rank'}, inplace = True)
ScoringMargin.rename(columns = {'Rank':'ScoringMargin_Rank'}, inplace = True)
ScoringOffense.rename(columns = {'Rank':'ScoringOffense_Rank'}, inplace = True)
StlsPerGame.rename(columns = {'Rank':'StlsPerGame_Rank'}, inplace = True)
ThreePtFGPct.rename(columns = {'Rank':'ThreePtFGPct_Rank'}, inplace = True)
ThreePtFGDef.rename(columns = {'Rank':'ThreePtFGDef_Rank'}, inplace = True)
ThreePtFGPerGame.rename(columns = {'Rank':'ThreePtFGPerGame_Rank'}, inplace = True)
TOMargin.rename(columns = {'Rank':'TOMargin_Rank'}, inplace = True)
TOPerGame.rename(columns = {'Rank':'TOPerGame_Rank'}, inplace = True)
WLPct.rename(columns = {'Rank':'WLPct_Rank'}, inplace = True)

In [5]:
# Confirm changes to column name
FTPct.head()

   FTPct_Rank                            Team  GM    W-L   FT  FTA   FT%
0           5  A&M-Corpus Christi (Southland)  33  23-10  550  696  79.0
1         150         Abilene Christian (WAC)  30  13-17  414  573  72.3
2         153       Air Force (Mountain West)  32  14-18  369  511  72.2
3          92                     Akron (MAC)  33  22-11  475  643  73.9
4         330              Alabama A&M (SWAC)  33  15-18  425  649  65.5

In [6]:
# Adding Team and AstPerGame Rank columns to a new dataframe for yearly 
df = AstPerGame[['Team', 'AstPerGame_Rank']].copy()
print(df)

                               Team  AstPerGame_Rank
0    A&M-Corpus Christi (Southland)               29
1           Abilene Christian (WAC)               28
2         Air Force (Mountain West)               39
3                       Akron (MAC)              153
4                Alabama A&M (SWAC)              202
..                              ...              ...
347            Wright St. (Horizon)               51
348         Wyoming (Mountain West)              315
349               Xavier (Big East)                1
350               Yale (Ivy League)               70
351        Youngstown St. (Horizon)               34

[352 rows x 2 columns]

In [7]:
# Prepare remaining columns to be inserted into new DF

APG = AstPerGame['AstPerGame_Rank']
ATOR = AstTORatio['AstTORatio_Rank']
BPG = BlocksPerGame['BlocksPerGame_Rank']
FGP = FldGlPct['FldGlPct_Rank']
FGPD = FldGlPctDef['FldGlPctDef_Rank']
FPG = FoulsPerGame['FoulsPerGame_Rank']
FTP= FTPct['FTPct_Rank']
RM = ReboundMargin['ReboundMargin_Rank']
SD = ScoringDefense['ScoringDefense_Rank']
SM = ScoringMargin['ScoringMargin_Rank']
SO = ScoringOffense['ScoringOffense_Rank']
SPG = StlsPerGame['StlsPerGame_Rank']
TPFGP = ThreePtFGPct['ThreePtFGPct_Rank']
TPFGD = ThreePtFGDef['ThreePtFGDef_Rank']
TPFGPG = ThreePtFGPerGame['ThreePtFGPerGame_Rank']
TOM = TOMargin['TOMargin_Rank']
TOPG = TOPerGame['TOPerGame_Rank']
WLP = WLPct['WLPct_Rank']

In [10]:
# Insert New Columns into Dataframe

df['AstTORatio_Rank'] = ATOR
df['BlocksPerGame_Rank'] = BPG
df['FldGlPct_Rank'] = FGP
df['FldGlPctDef_Rank'] = FGPD
df['FoulsPerGame_Rank'] = FPG
df['FTPct_Rank'] = FTP
df['ReboundMargin_Rank'] = RM
df['ScoringDefense_Rank'] = SD
df['ScoringMargin_Rank'] = SM
df['ScoringOffense_Rank'] = SO
df['StlsPerGame_Rank'] = SPG
df['ThreePtFGPct_Rank'] = TPFGP
df['ThreePtFGDef_Rank'] = TPFGD
df['ThreePtFGPerGame_Rank'] = TPFGPG
df['TOMargin_Rank'] = TOM
df['TOPerGame_Rank'] = TOPG
df['WLPct_Rank'] = WLP

In [11]:
# confirm addition of columns 
df.head()

,Team,AstPerGame_Rank,AstTORatio_Rank,BlocksPerGame_Rank,FldGlPct_Rank,FldGlPctDef_Rank,FoulsPerGame_Rank,FTPct_Rank,ReboundMargin_Rank,ScoringDefense_Rank,ScoringMargin_Rank,ScoringOffense_Rank,StlsPerGame_Rank,ThreePtFGPct_Rank,ThreePtFGDef_Rank,ThreePtFGPerGame_Rank,TOMargin_Rank,TOPerGame_Rank,WLPct_Rank
0,A&M-Corpus Christi (Southland),29,75,341,108,233,318,5,64,251,48,17,22,48,127,124,44,233,55
1,Abilene Christian (WAC),28,66,298,152,342,346,150,252,207,131,100,19,165,314,214,5,203,244
2,Air Force (Mountain West),39,63,73,77,221,193,153,305,90,216,291,243,98,10,85,278,164,235
3,Akron (MAC),153,80,249,181,123,101,92,90,83,49,110,222,105,215,28,110,57,67
4,Alabama A&M (SWAC),202,315,65,209,96,309,330,307,199,245,221,48,38,212,231,160,334,225

In [ ]:
# Remove index while exporting
df.to_csv('/Users/bryanwenger/Desktop/Desktop_Master/Coding/github_projects/marchmadness_2023/MarchMadness_2023/data_sets/Yearly_Data_2023.csv',index=False)